name: numbadev
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numba/label/dev::llvmlite
  - numpy
  - scipy
  - jinja2
  - cffi
  # developer aids
  - python-lsp-server
  - pylsp-mypy
  - conda-lock
  - setuptools
  - ipython
  - debugpy
